[package]
name = "student-report-aau"
version = "0.1.2"
entrypoint = "template.typ"
authors = ["Kresten Laust <https://github.com/krestenlaust>"]
license = "MIT" #todo
description = "Official student report template at Aalborg University (AAU) recreated in Typst"
keywords = ["academic", "report", "thesis", "university", "aau"]
categories = ["document", "template"]
disciplines = ["computer science"]

[template]
path = "."
entrypoint = "main.typ"
thumbnail = "thumbnail.jpg"
