name: Build Typst document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile single-file demo
        uses: lvignoli/typst-action@main
        with:
          source_file: main_single_file_demo.typ
      
      - name: Compile full demo
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            main_single_file_demo.pdf
            main.pdf