name: Build Typst document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Typst single-file compile
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            main_single_file_demo.typ
      
      - name: Typst folder compile
        uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.5.0'
      - run: typst compile main.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            main_single_file_demo.pdf
            main.pdf