name: Build Typst document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile singlefile-template
        uses: lvignoli/typst-action@main
        with:
          source_file: singlefile-template/main.typ
      
      #- name: Compile report-template
      #  uses: lvignoli/typst-action@main
      #  with:
      #    source_file: report-template/main.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            singlefile-template/main.pdf
          #report-template/main.pdf